# Introduction

## The common disease/common variant framework

Complex diseases are those caused by a mixture of genetic, environmental and lifestyle factors. The object of study of this thesis is the study of methodologies to identify such genetic factors. This is of paramount importance for prevention, understanding the etiology of the disease, and provide better treatments. 

The genetic architecture of a trait is the number of variants that contribute to the risk, as well as their allelic frequencies, effect sizes, and their genetic mode of action (e.g. dominant or recessive). From this point of view, complex diseases are easier to understand by their contrast with Mendelian traits. The latter are caused by a single locus with strong effects, and hence they follow the Mendelian rules of inheritance. In essence, and barring considerations on reduced penetrance, whether an individual will develop a Mendelian disease or not depends exclusively on the two alleles on that particular locus, and its genetic mode of action. In contrast, the genetic architecture of complex is modelled by the *liability-threshold model*, an extension to binary traits of the infinitesimal model used to describe the genetics of continuous phenotypes like height. Under the infinitesimal model, a trait is shaped by many Mendelian alleles, each of them with a small contribution to the trait [@barton_infinitesimal_2017]. The liability-threshold model computes a risk score for an individual based on the contribution of each of the alleles in the genetic architecture, plus the contribution of the environment. If such risk score surpasses a given threshold, disease will ensue.

Because the risk alleles have such small effect sizes, they are not under strong purifying selection. This allows them to be common (>1-5% of the population), unlike the mutations causing Mendelian diseases, which are rare, as they strongly decrease the fitness of the individual [@manolio_finding_2009]. In consequence, the study of the genetics of complex diseases relies on the *common disease, common variant* hypothesis: common diseases are partly attributable to allelic variants present in more than 1-5% of the population, which cause, by themselves or in combinations, small increments in risk (1.1 - 1.5-fold). However, another consequence of this limited effect size is that only weak associations between causal variants and phenotypes can be expected. Again, this notion is radically different from Mendelian diseases, where every carrier of the risk allele develops the disease under complete penetrance. In summary, the study of the genetics of complex diseases requires the identification of a large number of risk variants, among a humbling 686 million known variants in humans [@required]. 

The modern unit of genetic variation are single base-pair changes in the DNA sequence, called single-nucleotide polymorphisms or SNPs [@bush_chapter_2012]. SNPs are, by far, the most common form of genetic variation in humans. SNPs usually involve two alleles, meaning that in a population there are two possible base-pairs for a genetic position. SNPs are characterized by their minor-allele frequency, that is, the frequency of the least common allele in the population.

## Epistasis

Epistasis is the phenomenon where the effect of one locus on the phenotype depends on the state one or more additional loci. It has two variants: biological and statistical [@moore_traversing_2005]. Biological epistasis refers to the physical interaction occurring between the loci, for instance via their protein products. It is possibly a consequence of the redundancy of biological mechanisms, which would require altering all redundant biological mechanisms to aleter a biological function [@niel_survey_2015]. Multiple cases of biological epistasis contributing to phenotypes in model organisms have been reported in the literature [@required]. Statistical epistasis, in constrast, is the observation than the association between one locus and the phenotype changes across the level of the other locus. In essence, statistical epistasis refers to the biological epistasis detectable at the population level. In this regard, links between epistasis and complex diseases like Alzheimer's disease [@combarros_epistasis_2009], inflammatory bowel disease [@cho_identification_1998] and hypertension [@kimura_multilocus_2012] have been found. As in this thesis I worked exclusively in the detection of the latter kind, for brevity's sake I will refer to it simply as *epistasis*.

Despite the links between epistasis and complex disease mentioned above, estimating the magnitude of its contribution to complex diseases in humans is hard [@gusareva_practical_2014]. Nonetheless, [@zuk_mystery_2012] proposed that incorrectly accounting for epistasis might be behind the so-called *missing heritability* of complext traits. Additionally, studies of traits model organisms suggest that epistasis plays a key role of their genetic architecture [@required]. This motivates further studying the involvement of epistasis in complex diseases.

## Genome-wide association studies {#intro-gwas}

Genome-wide association studies (GWAS) are experiments where a high number of genetic variants are systematically surveyed on large cohorts to find phenotype-genotype associations [@bush_chapter_2012]. In the classical GWAS setting, a statistical test for association is conducted between each variant and the phenotype of interest. Often, that statistical test is a logistic regression, which allows using additional variables that might act as confounders. Then the "best hits", conventionally variants with a genome-wide P-value < 5 \texttimes 10^{-8}^, undergo a follow-up study on an independent cohort. Many fields that profit from this ability to survey a sample genome are using GWAS, especially in personalized medicine (e.g. pharmacogenomics). In consequence, GWAS has become a paragon of translational bioinformatics. The ultimate goal is to be able to identify individuals at genetic risk, as well as to understand the molecular basis of the disease.

The build 153 of dbSNP compiled over 667 million variants in humans. However GWAS do not need to survey all of them to obtain a representative view of the genome. Instead, GWAS exploits the correlations between the variants as a consequence of the genetic history, a phenomenon known as linkage disequilibrium (LD). Thanks to LD, GWAS survey the whole genome in an inexpensive fashion using SNP arrays that contain only need a small fraction of the known variants [@visscher_10_2017]. In consequence, the SNPs associated with a disease are likely not the causal ones, simply close and in LD with the causal variant.

Since the first GWAS in the late 2000s, they have shed light into the genetics of complex diseases, identifying more than 70000 variant-trait associations [@buniello_nhgri-ebi_2019]. First, GWAS confirmed the common disease / common variant hypothesis, that many loci with small effect sizes shape most of the variance of complex traits [@visscher_10_2017]. GWAS have also revealed widespread pleiotropy, as the same genomic regions are often found in association to multiple traits [@visscher_10_2017]. This has profound implications, showing how interrelated different biomolecules are. In fact, holistic models that add nuances to the infinitesimal model have been suggested, like the *omnigenic model* [@boyle_expanded_2017]. The omnigenic model postulates that only a few core genes are directly implicated in the disease, and alterations on them have a strong effect. But alterations in many other, unrelated, genes can also lead to disease as they propagate through biological networks to affect the functionality of those core genes. A more complete view of biological networks and disease is available in Chapter \@ref(genesis).

<!-- TODO READ LATEST REVIEWS ON GWAS -->

### Challenges {#intro-gwas-challenges}

In the case of height, 80% of the intra-population variability in height is due to genetic factors (h^2^ = 0.8) [@visscher_heritability_2008]. Three studies with a total sample size of 63k individuals (14k + 16k + 34k) identified 54 variants that are reliably associated with height. However, they only get to explain 5% of the phenotypic variance [@manolio_finding_2009]. The rest of the estimated genetic component is something alike "dark matter": we know it is there, as we can see its effects, we just cannot see it nor know what it is exactly. This situation is actually common to many complex phenotypes, and has been called the missing heritability problem. There are several candidates out there to explain this dark matter: a larger than expected number of variants with mild effects (difficult to find in underpowered setting of GWAS); rarer variants with strong effects; but also an overestimation of h^2^ by unconsidered epigenetics, dominance and epistatic effects; and even an inadequate accounting of shared environment among relatives. Of course, different traits will have different allelic architectures (number of variants, effects, type...). But even then, our knowledge is too limited to really assess it. The enigma of missing heritability is especially relevant when we deal with complex diseases. Missing heritability is a consequence of a few, inter-related challenges, which I describe below. My thesis involved developing methodologies that tackle these issues.

#### Low statistical power

Due to the low effects sizes implied by the common disease / common variant hypothesis, GWAS require large sample sizes, on the thousands. However, the number of biomarkers required to scan the whole genome is even larger, from hundreds of thousands to the millions. In consequence, GWAS is conducted in an ultradimensional setting, which altogether with the small effect sizes, leads to low statistical power [@button_power_2013]. Statistical power can be further reduced if the causal SNPs are in weak LD with the closest genotyped variants, for instance if they are rare [@visscher_10_2017]. Also when the phenotype is heterogeneous [@visscher_10_2017], as is common in complex diseases. This has with several implications. First, it implies by definition a small chance of discovering effects that are true. Second, it raises the probability of a discovery to be a false positive. Third, when an underpowered study discovers a true effect, it is likely that the effect size is overestimated. One practical consequence of this low power in GWAS studies, for example, is the difficulty to reproduce a GWAS result [@visscher_heritability_2008].

Visscher conducted a classical GWAS inquiring about the heritability of height [@visscher_heritability_2008]. Three studies with a total sample size of ∼63k individuals (14k + 16k + 34k) identified 54 variants that are reliably associated with height. However, there was an alarmingly low overlap between the causal SNPs identified in the different studies. The reasons for this are multiple. First, it dealt with SNPs that have a very limited effect size which require sample sizes of the order of tens of thousands to reliably identify one causal SNP. Second, hundreds of thousands of association tests are conducted, which requires being very stringent with the significant threshold in order to minimize type I errors. Lastly, the number of SNPs in a population is between one and two orders of magnitude above the number of SNPs surveyed in a chip [@wray_pitfalls_2013]. Hence, it is likely that the association we measure between most of the markers and the phenotype is due to the linkage disequilibrium with the true causal SNP(s). This further dilutes the association that we intend to measure.

Another consideration regarding GWAS is that most studies have been carried out on European ancestry populations, which has a reduced variability in comparison to other human populations [@visscher_heritability_2008]. In fact, studies on non-European populations have yielded a big number of new, intriguing variants.

#### Estimating individual risk

Ultimately, our goal is to estimate the full effect of the genetic factors for a patient. This involves moving moving from population-level associations, to an individual assessment [@wray_pitfalls_2013]. However, even in an hypothetical case where we know all the markers involved in a phenotype and their respective effect sizes, the $R^2$ of a linear predictor would be upper bounded by the heritability ($h^2$). This means that, at the patient level, we would only have a probabilistic estimate of their risk.

#### Population structure {#pop-structure}

The LD structure is population specific. Hence, GWAS designs must account for samples with different ancestries or, in other words, capture the population structure in the data. Failure to do so might lead to overestimating allelic and genotypic frequencies, reduce statistical power and produce spurious associations [@required]. Population structure can be captured by the principal components of the genotype matrix, and hence they are often used to account for it. For instance, a logistic regression using the main principal components as covariates is often used to obtain measures of association at the SNP level correcting by potentially confounding population structure. Approaches like EIGENSTRAT also use these PCs to detect population structure in the data.

#### Interpretability

By design, a genotyped SNP measures the association of the whole genomic region which is in LD with it. Hence, follow-up studies are needed to find the causal link between the region and the disease. A frequent strategy is identifying nearby genes [@wang_statistical_2018], as those are considered the functional unit of inheritance. Yet, mapping genomic regions to genes is not trivial. In the literature, we find three ways of of doing so. The first one is the physical mapping, which maps that region to the genes that whose genomic coordinates overlap with it. Often the gene boundaries are expanded by a fixed number of kilobases, as SNPs in promoters or nearby enhancers can affect gene expression [@segre_common_2010]. Nonetheless, physical mapping can be ambiguous due to the overlap between genes (Section \@ref(results:consensus)). The second SNP-gene mapping is through gene expression, when SNPs in the associated genomic region are eQTLs of a gene. In this regard, the GTEx project [@gtex_consortium_genetic_2017] is a useful source of tissue-specific eQTL. Gene expression mapping is not exempt of the overlap problem that occurs in the physical mapping. Solutions which consider LD patterns and the association across the whole genomic region have been proposed [@liu_abundant_2019]. The third SNP-gene mapping is based on the 3D structure of the genome, which causes distant genomic regions to be close in space [@required]. In this situation, SNPs in a genomic region are associated to genes in the neighboring region.

## Genome-wide association interaction studies

Genome-wide association interaction studies (GWAIS) share the experimental design with GWAS, but focus on the detection of epistasic associations. As opposed to GWAS, no standard GWAIS protocol exist yet , although some general recomendations have been issued [@gusareva_practical_2014; @ritchie_search_2018].

### Challenge: modelling epistasis

Due to the similar experimental design, GWAIS and GWAS share a number of challenges (Chapter \@ref(intro-gwas-challenges)). Nonetheless, such problems are often aggravated in GWAIS. For instance, a larger number of tests implies a further reduction of the statistical power. Interpretation is also more complicated, as two or more genomic region in LD with the genotyped SNP need to be examined for the causal variants [@gusareva_practical_2014]. However it presents two additional considerations, related to the multiple genetic scenarios in which epistasis can occur. For instance [@li_complete_2000] estimated that there are 50 different fully penetrant disease models involving two loci in epistasis.

First, in any epistasis related study, a number of arbitrary choices must be made, like the order of the explored interactions or the genetic encoding [@romagnoni_comparative_2019]. It must be settled what is the order of the interactions that are explored. For instance, fourth order epistasis involves four different loci jointly contributing to a phenotype. Nonetheless, as the number of interactions grows exponentially with the epistasis order, most methods and studies focus on second order epistasis.

Second, epistasis introduces the challenge of how the most appropriate way of detecting it. Multiple strategies to detect epistasis have been proposed, from logistic regression with an interaction term to deep learning. [@niel_survey_2015] reviews the main families of epistasis detection stategies. In general, this diversity comes from tackling different aspects of the computational and statistical issues that arise from the large number of potential interactions. Logistic regression [@required] for instance is exhaustive and easy to paralelize, but makes strong assumptions on the underlying relationship between the genotype and the phenotype. Hence, statistical power is compromised when that model is inaccurate. On the other hand, MDR [@moore_flexible_2006] is model-free and exhaustive, but is limited to case-control phenotypes and the inability to compute analitically the statistical power makes it slower. In Chapter \@ref(epi-network) we examine different epistasis detection methods, focusing on those that can account for a continuous phenotype.

## Diseases studied in this thesis

The bulk of my work in this thesis revolved aroung two complex diseases: breast cancer and inflammatory bowel disease.

### Breast cancer

Cancer is the name of a collection of related diseases. Specifically, all cancers undergo an uncontrolled proliferation of the patient cells, which spread into surrounding tissues. In a normal organism, cells grow and divide to maintain the tissue. As cells grow old, or accumulate too much damage, they undergo cell death and new cells will take their place. However, in cancer, this orderly process breaks down. Cells refuse to die when they get old, or  accumulate damage. New cells are formed even if they are not needed. In consequence they form purpose-less growths called tumors.

This abnormal behavior occurs as consequence of the alteration of crucial genes. These alterations can be inherited from our parents, or acquired during our lifetime, due to replication errors or exposure to DNA-damaging substances. As with any other phenotypic trait, the likelihood of developing cancer will be determined by the interplay between our genetic background and the environment: genetic backgrounds may favor or hinder the acquisition of mutations, and so do environmental factors.

Breast cancer occurs when breast cells undergo this uncontrolled proliferation. In most of the cases they begin in the ducts that carry the milk to the nipple. However the tumor can originate in other tissues, mainly the milk-producing gland.

Breast cancer is the second most commonly diagnosed cancer among women, after non-melanoma skin cancer. It is also the second leading cause of cancer deaths after lung cancer. It is mostly a women's disease: only about 1% of the diagnosed cases are in men. Among the most important risk factors for breast cancer we can highlight age, family history, reproductive history, usage of oral contraceptives and exposure to radiation. Most breast cancers occur after age 50 years.

Breast cancer is a very heterogeneous disease: while all the tumors appear in the same organ, the tissue where they originate, the molecular mechanism involved, the response to therapy, etc. vastly differ. In general, clinical decisions are based on the expression of 3 molecular markers: the expression of the endocrine receptors for estrogen and progesterone (ER and PgR, respectively) and the overexpression of the HER2 gene. The proteins these three genes code for are targets for chemotherapy. Based on the results, we distinguish three main breast cancer subtypes: hormone receptor positive, HER2 positive and triple negative.

- Hormone receptor positive :: Hormone receptor positive tumors include the tumors expressing ER and/or PR, which respectively  depend on estrogen and/or progesterone to grow. They happen mostly in postmenopausal women. HR+/HER2- also known as LuminalA are the majority of breast cancers (60-75%) and they present the best prognosis.
- HER2 positive :: HER2+ tumors depend on the protein HER2/neu (human epidermal growth factor receptor 2) to proliferate, which they over-express. HR+/HER2+ (also known as LuminalB) constitutes 10% of the cases, while HR-/HER2 (also known as HER2-enriched) involves 5% of them. There are a couple of very effective drugs against it.
- Triple-negative :: Triple-negative tumors lack the expression of all three of ER, PgR and HER2. These patients present a worse prognosis than the rest, due to the aggressiveness of the tumor and the lack of a clear molecular target. Still, the main treatment is chemotherapy.

In the mid-19th century a French medical doctor, Pierre Paul Broca, reported for the first time a case of familial breast cancer [@nielsen_hereditary_2016]. Indeed, his wife acquired breast cancer, as many women in her family had for, at least, 4 generations. Cases of familiar breast cancer usually occur in women younger than 50 years, and bilateral primary breast tumors are frequent. Epidemiological studies later quantified the relative risk conferred by a the presence of multiple breast cancers in the family at 2.7. Moreover, they exhibit a higher likelihood of acquiring triple-negative breast cancer.

It wasn't until the late 20th century that two genes involved in DNA repair, BRCA1 and BRCA2, were associated with hereditary breast and ovarian cancer (HBOC). Some mutations in these genes increase the risk of developing breast cancer, giving respectively a 57–65% or 45–55% risk of developing breast cancer by age 70 among women. For that reason, BRCA1 and BRCA2 mutations are rare in most populations (1 of 400). 

HBOC follows an autosomal dominant inheritance pattern. While approximately 5–10% of all patients with breast cancer exhibit a monogenic predisposition to breast and ovarian cancer, only about 25% of them harbor BRCA1/2 mutations. Other 23 genes have been associated with familial breast and/or ovarian cancer (Table \ref{tab:HBOC_genes}). 

Nearly all known HBOC susceptibility genes encode tumor suppressors that participate in genome stability pathways (homologous recombination repair, replication fork stability, transcription–replication collisions, mismatch repair, and DNA damage signaling, checkpoints and cell death; see Appendix A for more information).

#### The GENESIS dataset {#genesis-dataset}

The GENE Sisters (GENESIS) study was designed to investigate risk
factors for familial breast cancer in the French population
[@sinilnikova_genesis:_2016]. Index cases are patients with infiltrating
mammary or ductal adenocarcinoma, who had a sister with breast cancer,
and who have been tested negative for BRCA1 and BRCA2 pathogenic
variants. Controls are unaffected colleagues and/or friends of the
cases, born around the year of birth of the corresponding case ($\pm 3$
years). We focused on the 2 577 samples of European ancestry, of which
1 279 are controls and 1 298 are cases. The genotyping was performed
using the iCOGS array, a custom Illumina array designed to study genetic
susceptibility of hormone-related cancers [@sakoda_turning_2013]. It
contains 211 155 SNPs, including SNPs putatively associated with breast,
ovarian, and prostate cancers, SNPs associated with survival after
diagnosis, and SNPs associated to other cancer-related traits, as well
as functional candidate variants in selected genes and pathways.

### Inflammatory bowel disease

Inflammatory bowel disease (IBD) is a group of diseases that, as the name indicates, share a common theme of inflammation of the intestines. The two main forms of IBD are ulcerative colitis and Chron's disease. TODO

#### The IIBDGC dataset

The International Inflammatory Bowel Disease Genetics Consortium carried out a case-control GWAS on ulcerative colitis and Chron's disease [@ellinghaus_analysis_2016]. The dataset contain 66 280 samples, out of which 32 622 are cases and 33 658 are controls. The Immunochip SNP array was used for the genotyping [@required], which contains 196,524 polymorphisms, with a special focus on immunogenetics.

## Network view of complex diseases

<!-- motivation (link to challenges, biology as networks) -->

Human biology is notoriously complicated, as sheer numbers demonstrate: to form a 70kg man, 3.0 \texttimes 10^13^ cells [@sender_revised_2016] assemble and interact to produce and maintain 79 organs. To achieve that level of complexity, human cells depend on their genetic material, carefully tuned by epigenetics and enabled by a favorable environment. In terms of genetics, the object of my work, a human diploid genome is 6.4 billion base pairs long, and encodes 30,000 genes, of which TODO encode for a protein and TODO are RNA genes. DNA, proteins and RNA are in constant interplay with each other, with the metabolites, and with the environment. Proteins physically interact with each other in highly specific ways (protein-protein interactions or PPIs). If such interactions are stable enough, proteins can assemble into large complexes to carry out particular functions. But proteins also interact with DNA to regulate gene expression (transcription factor - DNA interactions). And so on: enzymes interact with their metabolites, hormones with their receptors, the individual with their environment, etc. At a fundamental level, a person and their traits are just the emerging pattern born from the interaction of all these factors. Hence, biology, from ecosystems to molecular biology, cannot be understood if not as an interplay. Mindful of this, and enabled by the omics technologies of the 21st century, researchers have strived to capture these relationships. Among all the possible biological relationships, in this thesis I focused on protein-protein interactions, including protein complexes, as their coverage is larger and their properties better understood. Such interactions are available in databases like HINT [@das_hint_2012], The BioGRID [@oughtred_biogrid_2019] or IntAct [@hermjakob_intact_2004].

Relationships between pairs of entities can be mathematically formalized as a network, which makes them analytically approachable. In such networks, often proteins or genes are the nodes, which are connected by edges in a pairwise fashion when they are related. Although the edges might have directionality, often PPIN are undirected, as the direction of the edges is often unknown (transitory interactions), or inexistant (co-complexes) [@barabasi_network_2011].

The field of systems biology relies on the assumption that the network accurately captures the context it requires to carry out its biological function. We can distinguish three levels of network properties: properties of individual nodes (local), the joint properties of groups of nodes (mesoscale), and the properties over the whole network (global). Indeed, at all three levels biological networks are structured, very differently from random networks [@barabasi_network_2011].

At the global level, for instance, the degree distribution, which represents the distribution of the number of edges per node, follows a power-law distribution. This implies that, at the local level, a few genes participate in the majority of the edges. Such nodes are called *hubs*. Importantly, this node property is informative of the gene function: *in utero* essential genes, like knots preventing the network from falling apart, tend to be hubs. An important consequence of the structured degree distribution at the mesoscale level is the emergence of modules, subsets of nodes densely interconnected to each other, and sparsely to the rest. Such modules are often associated with biological function towards which all nodes jointly contribute [@mitra_integrative_2013]. 

Another global property of a graph is the distribution of distances between pairs of nodes, that is, how many edges must be passed to travel from one node to another. Such is the notion of path between nodes. Often we are interested in the *shortest* path, for they reveal the fastest way information can flow from one node to another. An examination of the distribution of shortest paths in biological networks, shows that all nodes are close to each other [@barabasi_network_2011]. Such networks are called *small world networks*.

### Networks in disease

Examining how these biological networks relate to disease, and the topology around disease genes produces a nuanced approach to disease: cut the knot in the center of the web that keeps it all together, and it all will fall off; cut a bunch of peripheral, less important nodes around it, the outcome might be the same. In other words, there are many ways of producing the same disease [@leiserson_network_2013]. 

The properties of biological networks enumerated above lay down the foundations of the use of biological networks to study disease genes. For instance, they justify the *local hypothesis*, which expects genes involved in a disease to interact with each other [@barabasi_network_2011]. Also the disease module hypothesis, which expects genes involved in the same disease to share a module. Experimentally, network propagation experiments highlight the differential topological properties of disease genes and biological networks. Network propagation refers to methods that use all the possible paths in the network to re-rank the genes on it [@cowen_network_2017]. They include heat diffusion, random walk, graph kernels and even Google's PageRank. In essence, for these methods, association of a node with a phenotype can be thought of as a volume of water: the more strongly associated, the more voluminous. Generically, each node starts with an initial volume which, iteratively, gets distributes its liquid among its neighbors. Equivalently, that node will receive a share from its neighbors'. The expectation is that truly associated genes will be densely interconnected to each other, forming cycles and modules that will keep the water from diffusing to other, uninvolved genes. After a number of steps the volume of water in each node is re-evaluated, and used to re-prioritize the genes. Using network propagation  [@huang_systematic_2018] recently showcased the differential topological properties of disease genes. Across different biological networks, they were able to retrieve disease-related genes with varying success using only a subset of them and random walk with restart.

<!-- TODO double check 
tend to be non-essential genes located in the periphery
-->

Indeed, disease genes exhibit different properties than non-disease genes in disease [@pinero_uncovering_2016; @cai_broker_2010; @furlong_human_2013; @barabasi_network_2011]. For starters, disease genes are not hubs [@cai_broker_2010; @das_hint_2012], but tend to be non-essential genes located in the periphery. This is coherent with a evolutionary mindset, where mutations in essential genes would be highly deleterious, even resulting in embryonic lethality. However, this enrichment is driven mainly by cancer genes [@pinero_uncovering_2016]. Additionally, disease genes tend to be bottlenecks i.e. the sole link between many peripheral genes and the rest of the network [@cai_broker_2010], suggesting disease arise when these vulnerable regions of the network break down. 

These properties, however, do not affect equally all types of disease genes. Many of the aforementioned properties do not extend to genes identified through GWAS [@cai_broker_2010]. However, differences arise even when comparing genes involved in complex diseases with those involved in Mendelian ones.

### Network-guided approaches to disease study 

As exemplified in the previous section, networks can be leveraged on to gain insight of the biology of the disease. Below I summarize several ways of doing that which I have worked on during my thesis.

#### High-score subnetwork search

One of the focuses of my thesis was the study of networks where the nodes have been scored by their association to the disease. The scores might come from omics experiments, or from *a priori* knowledge of disease genes. In essence, such methods look for connected subnetworks made of nodes with high scores. Lacking a term broadly agreed in the community, I refer to such algorithms as high-score subnetwork search. Although heterogeneous, to some extent all such approaches are based on the *guilt-by-association principle*: nodes nearby other nodes associated to the disease are suspect of being associated themselves, even if their association is non-significant by conventional standards. However, taking only the genes associated with those associated would be prone to false positives, as often networks include edges that are not relevant for the biological problem at hand. There are several high-score subnetwork search methods available in the literature. Essentially, they differ in the considerations they make on how the solution looks like. In Chapter \@ref(genesis) we describe a representative set of these methods, critically discuss their performance at biomarker discovery on the GENESIS dataset, and discuss their shortcomings.

<!--
TODO
MOVE TO THE GENESIS PAPER
Nonetheless, these methods are not exempt of problems. For instance, these methods are heavily affected by the *small world* nature of biological networks, which make it relatively easy to find that two associated nodes are close [@pinero_uncovering_2016]. Additionally, when the biological network contains edges that are irrelevant for a particular disease the complexity of the problem is increased, and the signal decreased. ALso [@mitra_integrative_2013].
-->

#### Aggregation of networks

Due to the methodological nature of my PhD, often I had multiple subnetworks providing complementary approaches to the same diseases. In consequence, I was interested in integrating them into a single subnetwork, which I would analyze. TODO DISCUSS CONSENSUS CLUSTERING [@lancichinetti_consensus_2012]. [@wang_similarity_2014] proposed a network fusion approach to integrate similarity matrices from different omics experiments on the same patients.

In Chapter \@ref(genesis) we discuss a naive way of aggregating subnetworks from different high-score subnetwork search algorithms, were the edges are unweighed. In Chapter \@ref(epi-network), we discuss how to apply consensus clustering to networks coming from different epistasis detection methods, whose edges are weighed by the confidence they exist.

#### Module detection

Given a biological network, finding sets of nodes densely interconnected to each other and sparsely to the rest reveals functional units within the network [@mitra_integrative_2013]. In Appendix \@ref(smartas) we apply module detection techniques to a subnetwork of genes with abnormal splicing in cancer.

## Contributions

The object of my thesis was the methodological study and application of network methods to GWAS data. In essence, networks contain prior information, which can be traded for statistical astringency in our analysis. In other words, if genes strongly associated to a disease, albeit non-significantly so, are interconnected in an underlying biological network, we are likelier to believe they represent a consistently altered biological mechanism.

My first approach to the problem involved the work on SConES [@azencott_efficient_2013]. This algorithm, and my work on it are described in detail in Chapter \@ref(martini). In summary, I worked on applying SConES to case-control datasets, and strategies to parametrize it. Regarding the former, originally SConES implemented SKAT to measure the association between a SNP and a phenotype, a statistic developed for continuous phenotypes. As I focused on case-control studies, it made sense to implement other measures of association. Hence, I implemented both a 1 d.f. $chi^2$ statistical test, and a logistic regression, to perform case-control GWAS in the presence of covariates. Regarding the latter, SConES has two parameters, $\eta$ and $\lambda$, which control the sparsity and the inter-connectedness of the selected SNPs, respectively. The original implementation of SConES I worked on, EasyGWAS', set up these parameters by cross-validation, selecting those that lead to more stable solutions. However, manual inspection of the results showed that in some cases, slight changes in $\eta$ and $\lambda$ could recover known biomarkers of breast cancer in GENESIS. With those cases in mind, I decided to use two rounds of cross-validation of the parameters in my experiments: in a first round, a wide range of hyperparameters is examined; in a second round, a finer grid built around the best hyperparameters in the previous iteraction is built. Additionally, I explored the impact of alternative critera, other than stability, on hyperparameter selection. In that regard, we explored the effect of measures like BIC, AIC, and AICc, which score a set of features based on both their sparsity and the accuracy of a linear classifier built on them. The product of my work is published in *martini*, an R package published in Bioconductor. 

In collaboration with Dr. Nadine Andrieu and Dr. Fabienne Leuseur, and working closely with Dr. Christine Lonjou, I applied SConES and other high-score subnetwork search to the GENESIS dataset (Chapter \@ref(genesis-dataset)). Our goal was to find new biomarkers for breast cancer susceptibility. My work on GENESIS is explained in Chapter \@ref(genesis). In summary, I applied six difference network-based, biomarker discovery methods to the GENESIS dataset. The methods provide a representative view of the high-score subnetwork search field. We perform a methodological comparison and a benchmark of the methods, highlighting their strenghts and weaknesses. Finally, we conclude that combining the methods provide a more complete answer than any of the individual solutions. Our network analysis recovers both genes and genomic regions previously found in association with breast cancer susceptibility, as well as new genes. Importantly, all of those genes are tied in a subnetwork, providing a rationale on how alterations on those genes might lead to disease.

In 2019, when I started working on epistasis detection, we established a collaboration with Prof. Dr. Dr. Kristel Van Steen, from University of Liège. Specifically, I worked closely with Diane Duroux, a PhD student in her research group. Our goal was to build an epistasis gene network of inflammatory bowel disease. We discuss our efforts in this regard in Chapter \@ref(epi-network). For that purpose, we surveyed suitable epistasis detection methods, applied them to the IIBDGC dataset, and integrated the solution. However, as a previous step we needed to appropriately map epistatic SNP networks to epistatic gene networks. We describe this work in Chapter \@ref(epi-snp2gene). In summary, we examined and evaluated four different mappings (physical, eQTL, chromatine, and the three together).

In collaboration with Dr. Makoto Yamada and Dr. Samuel Kaski, I developed block HSIC Lasso, a general-purpose non-linear feature selector. The work involved modifying an existing algorithm, HSIC Lasso, to reduce its memory consumption. On top of that, we worked on improving its performance, and on solving numerical issues in edge cases. The algorithm is implemented as the Python package pyHSICLasso, available on both PyPI and GitHub. Then, I characterized the algorithm and applied it to several biological datasets. Crucially, three of the datasets were GWAS, which was a milestone in terms of the number of features block HSIC Lasso can handle. Thanks to this work, we analyzed the impact of considering non-redundancy and non-linear models when selecting SNPs for patient classification. We describe the algorithm and our conclusions in the article *Block HSIC Lasso: model-free biomarker detection for ultra-high dimensional data* published in the proceedings of the ISMB/ECCB 2019 [@climente-gonzalez_block_2019]. The full manuscript is available in Appendix \@ref(block-hsic-lasso). It was made possible by a scholarship from RIKEN AIP, which allowed me to spend 3 months in Dr. Yamada's laboratory in Kyoto.

Additionally, I continued working on the involvement of alternative splicing in cancer. During 2016 and early 2017, we prepared the answer to reviewers for the article *The functional impact of alternative splicing in cancer*, which was published in Cell Reports in August 2017 [@climente-gonzalez_functional_2017]. The full manuscript is available in Appendix \@ref(smartas). In the same dates, I explored evidence of epistasis in cancer, looking for mutual exclusivity between alterations in alternative splicing and somatic mutations. We searched evidence of mutual exclusivity at both the gene and the pathway level. Among others, we found a compelling pattern in GATA3. This finding was published in Cell Reports in March 2018, in the broader article *Systematic analysis of splice-site-creating mutations in cancer* [@jayasinghe_systematic_2018]. The full manuscript is available in Appendix \@ref(scm). In addition, I put compiled the code required for the analyses in [@climente-gonzalez_functional_2017], and created a Python package with a clean interface. The package, *spada*, is available in both PyPI and GitHub. This package searches alterations of alternative splicing, and maps them to functional consequences at the protein level. Specifically, such consequences are the removal/addition of functional modules to the protein (e.g. domains) and the loss or gain of protein-protein interactions. Lastly, I applied *spada* to two leukemia datasets from TARGET. This last analysis is still on-going.

As part of the IC-3i International PhD Program, I was part of a doctoral mission, unrelated to my research, which would take one month of work every year. In 2017, it involved the preparation of the "3rd course on Breast Cancer, from clinics to biology". In 2018, it consisted on leading my own collaboration with Dr. Eyras, described above. In 2019, I helped mantaining the website of the Training Unit of Institut Curie. 

Lastly, I carried out my research committed to open, reproducible science. As such, all my projects have an associated, version-controlled, laboratory notebook, which includes as much data as I am allowed to share. All such laboratory notebooks are made out public when the paper is. All the scripts I developed are open source, under permissive MIT license. Specifically, I made an effort to develop project-independent tools, which are useful to anyone which needs similar to the ones I had. These tools are published on GitHub https://github.com/hclimente/gwas-tools.