# Funding acknowledgments {-}

This thesis was funded by the European Union's Horizon 2020 research and innovation program under the Marie Skłodowska-Curie [666003]. Additionally, the work presented in Appendix \@ref(block-hsic-lasso) was made possible by a scholarship from RIKEN AIP, which allowed me to spend 3 months in Makoto Yamada's laboratory in Kyoto. 

The co-authors of some chapters, and more generally the work presented in them, received additional sources of funding. Regarding Chapter \@ref(genesis), it was supported by funding from Agence Nationale de la Recherche (ANR-18-CE45-0021-01). Financial support for GENESIS resource and genotyping was provided by the Ligue Nationale contre le Cancer (grants PRE05/DSL, PRE07/DSL, PRE11/NA), the French National Institute of Cancer (INCa grant No b2008-029/LL-LC) and the comprehensive cancer center SiRIC, (Site de Recherche Intégrée sur le Cancer: Grant INCa-DGOS-4654). Computational resources for Chapters \@ref(epi-snp2gene) and \@ref(epi-network) have been provided by the Consortium des Équipements de Calcul Intensif (CÉCI), funded by the Fonds de la Recherche Scientifique de Belgique (F.R.S.-FNRS) under Grant No. 2.5020.11 and by the Walloon Region.